Repository cmarcellot/MyGreenWorld, pull requests merged in 2023-05, with the labels that each got.

#22 Mgwt 75 cash on click
  vuejs_app/public/Objets/tree.glb
  vuejs_app/src/App.vue
  vuejs_app/src/babylonjs/MainScene.ts
  vuejs_app/src/classes/City.ts
  vuejs_app/src/components/BabylonScene.vue
  vuejs_app/src/components/ProgCash.vue
Labels: enhancement

#23 Fix
  vuejs_app/src/babylonjs/MainScene.ts
Labels: enhancement

#25 feat: Add improvements in store menu
  vuejs_app/package-lock.json
  vuejs_app/public/objects/tree.glb
  vuejs_app/src/classes/Improvement.ts
  vuejs_app/src/components/StoreMenu.vue
Labels: enhancement

#26 feat: deblocage batiments
  vuejs_app/src/components/StoreMenu.vue
Labels: enhancement

#27 Mgwt 90 achat amelioration
  vuejs_app/src/classes/City.ts
  vuejs_app/src/components/StoreMenu.vue
Labels: enhancement

#28 feat : incremet gainPerSec
  vuejs_app/src/classes/City.ts
  vuejs_app/src/components/BabylonScene.vue
  vuejs_app/src/components/ProgCash.vue
Labels: enhancement

#29 Mgwt 93! redim scene
  vuejs_app/src/babylonjs/MainScene.ts
  vuejs_app/src/components/BabylonScene.vue
  vuejs_app/src/components/ProgCash.vue
  vuejs_app/src/components/ProgEcology.vue
  vuejs_app/src/components/StoreMenu.vue
Labels: enhancement

#30 Fix bug ecran de chargement
  vuejs_app/src/babylonjs/MainScene.ts
Labels: enhancement

#31 feat : add pictures and fix json
  vuejs_app/public/images/pic_BigHouse.jpg
  vuejs_app/public/images/pic_BigStore.jpg
  vuejs_app/public/images/pic_Building1.jpg
  vuejs_app/public/images/pic_Building2.jpg
  vuejs_app/public/images/pic_CarStore.jpg
  vuejs_app/public/images/pic_Caravan.jpg
  vuejs_app/public/images/pic_ClothingStore.jpg
  vuejs_app/public/images/pic_DIYStore.jpg
  vuejs_app/public/images/pic_FastFood.jpg
  vuejs_app/public/images/pic_Hotel.jpg
  vuejs_app/public/images/pic_LittleHouse.jpg
  vuejs_app/public/images/pic_Mansion.jpg
  vuejs_app/public/images/pic_Skyscraper.jpg
  vuejs_app/public/images/pic_SmallStore.jpg
  vuejs_app/public/images/pic_SuperMarket.jpg
  vuejs_app/public/images/pic_Villa.jpg
  vuejs_app/src/assets/storage.json
  vuejs_app/src/classes/Commerce.ts
  vuejs_app/src/classes/Living.ts
  vuejs_app/src/components/StoreMenu.vue
Labels: enhancement

#32 ajout des outils admin ( ajout d'argent)
  vuejs_app/src/components/StoreMenu.vue
Labels: enhancement

#33 Mgwt 87 nombre batiments
  vuejs_app/src/classes/City.ts
  vuejs_app/src/components/StoreMenu.vue
Labels: enhancement

#35 MGWT Add keyboard controls and gravity
  vuejs_app/src/babylonjs/MainScene.ts
Labels: enhancement

#36 fix word debloque to debloquee
  vuejs_app/src/components/StoreMenu.vue
Labels: wontfix

#41 feat: add gain per click and text in store menu (improvement)
  vuejs_app/src/classes/City.ts
  vuejs_app/src/classes/Improvement.ts
  vuejs_app/src/components/StoreMenu.vue
Labels: enhancement

#44 feat: save with local storage
  vuejs_app/src/App.vue
  vuejs_app/src/assets/storage.json
  vuejs_app/src/classes/City.ts
  vuejs_app/src/components/StoreMenu.vue
Labels: enhancement

#45 feat: fix a visibility bug
  vuejs_app/src/babylonjs/MainScene.ts
Labels: bug

#46 feat: update skybox
  vuejs_app/public/environments/grey_sky.env
  vuejs_app/src/babylonjs/MainScene.ts
  vuejs_app/src/components/BabylonScene.vue
Labels: enhancement

#51 Revert "feat: fix a visibility bug"
  vuejs_app/src/babylonjs/MainScene.ts
Labels: bug

#52 fix : bug progress bar, bug speed, bug treeSound
  vuejs_app/src/babylonjs/MainScene.ts
  vuejs_app/src/components/BabylonScene.vue
Labels: bug

#53 feat: add border for the map
  vuejs_app/src/babylonjs/MainScene.ts
Labels: enhancement

#54 feat: add possibility to mute and unmute
  vuejs_app/package-lock.json
  vuejs_app/package.json
  vuejs_app/src/App.vue
  vuejs_app/src/babylonjs/MainScene.ts
  vuejs_app/src/babylonjs/SoundManager.ts
  vuejs_app/src/classes/City.ts
  vuejs_app/src/components/ProgEcology.vue
  vuejs_app/src/components/StoreMenu.vue
  vuejs_app/src/main.ts
Labels: enhancement

#55 fix ref: MGWT-114
  vuejs_app/src/babylonjs/MainScene.ts
  vuejs_app/src/components/StoreMenu.vue
Labels: bug

#56 Mgwt 112 corriger les gains des batiments
  vuejs_app/src/assets/storage.json
  vuejs_app/src/classes/City.ts
  vuejs_app/src/components/ProgCash.vue
  vuejs_app/src/components/StoreMenu.vue
Labels: bug

#57 feats: Comment centrales electriques menu
  vuejs_app/src/components/StoreMenu.vue
Labels: bug

#58 Mgwt 124 ajouter modifier les montants dans admintools
  vuejs_app/src/components/StoreMenu.vue
Labels: bug

#59 Mgwt 124 ajouter modifier les montants dans admintools
  vuejs_app/src/components/StoreMenu.vue
Labels: bug

#60 feat: update ecology and fixe tooltip
  vuejs_app/src/assets/storage.json
  vuejs_app/src/components/StoreMenu.vue
Labels: enhancement

#63 refs: MGWT-127
  vuejs_app/src/classes/City.ts
Labels: bug

#64 Develop
  vuejs_app/package-lock.json
  vuejs_app/package.json
  vuejs_app/public/des-arbres.ico
  vuejs_app/public/environments/grey_sky.env
  vuejs_app/public/index.html
  vuejs_app/src/App.vue
  vuejs_app/src/assets/storage.json
  vuejs_app/src/babylonjs/MainScene.ts
  vuejs_app/src/babylonjs/SoundManager.ts
  vuejs_app/src/classes/City.ts
  vuejs_app/src/classes/Commerce.ts
  vuejs_app/src/classes/Energy.ts
  vuejs_app/src/classes/Improvement.ts
  vuejs_app/src/classes/Living.ts
  vuejs_app/src/components/BabylonScene.vue
  vuejs_app/src/components/ProgCash.vue
  vuejs_app/src/components/ProgEcology.vue
  vuejs_app/src/components/StoreMenu.vue
  vuejs_app/src/main.ts
Labels: Versionning
